const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
const GET_ACCOMMODATION_BY_ID = "GET_ACCOMMODATION_BY_ID";
const GET_SERVICES = "GET_SERVICES"
const GET_NEXT_ACCOMMODATIONS = "GET_NEXT_ACCOMMODATIONS";
const GET_FILTERED_ACCOMMODATION = "GET_FILTERED_ACCOMMODATION"
const GET_LOCATIONS = "GET_LOCATIONS";
const GET_COUNTRIES = "GET_COUNTRIES"
const GET_CITIES = "GET_CITIES"
const ORDER_BY_RATING = "ORDER_BY_RATING";
const CLEAR_DETAIL = "CLEAR_DETAIL";
const LOGIN_USER = "LOGIN_USER";
const LOGIN_GOOGLE = "LOGIN_GOOGLE";
const REGISTER_USER = "REGISTER_USER";
const GET_USER_DATA = "GET_USER_DATA";
const SET_RESERVATION_DATA = "SET_RESERVATION_DATA"
const UPDATE_USER_INFO = "UPDATE_USER_INFO";
const LOG_OUT = "LOG_OUT";

export {
  ORDER_BY_RATING,
  GET_ACCOMMODATIONS,
  GET_ACCOMMODATION_BY_ID,
  GET_SERVICES,
  GET_NEXT_ACCOMMODATIONS,
  GET_FILTERED_ACCOMMODATION,
  GET_COUNTRIES,
  GET_CITIES,
  GET_LOCATIONS,
  CLEAR_DETAIL,
  LOGIN_USER,
  LOGIN_GOOGLE,
  REGISTER_USER,
  GET_USER_DATA,
  SET_RESERVATION_DATA,
  UPDATE_USER_INFO,
  LOG_OUT
}