const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
const GET_ACCOMMODATION_BY_ID = "GET_ACCOMMODATION_BY_ID";
const ORDER_BY_RATING = "ORDER_BY_RATING";

export {
  GET_ACCOMMODATIONS,
  GET_ACCOMMODATION_BY_ID,
  ORDER_BY_RATING
}