const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
const GET_ACCOMMODATION_BY_ID = "GET_ACCOMMODATION_BY_ID";
const GET_SERVICES = "GET_SERVICES"
const GET_NEXT_ACCOMMODATIONS = "GET_NEXT_ACCOMMODATIONS";
const GET_FILTERED_ACCOMMODATION = "GET_FILTERED_ACCOMMODATION"
const ORDER_BY_RATING = "ORDER_BY_RATING";  
const CLEAR_DETAIL = "CLEAR_DETAIL";

export {
  GET_ACCOMMODATIONS,
  GET_ACCOMMODATION_BY_ID,
  GET_SERVICES,
  GET_NEXT_ACCOMMODATIONS,
  ORDER_BY_RATING,
  GET_FILTERED_ACCOMMODATION,
  CLEAR_DETAIL
}